<?php

declare(strict_types=1);

return [
    'admin' => [
        'standards' => [
            'label' => 'ISO Standards',
            'table' => 'iso_standards',
            'primary_key' => 'id',
            'key_type' => 'string',
            'timestamps' => ['createdAt', 'updatedAt'],
            'list_columns' => ['code', 'name', 'year', 'active'],
            'default_sort' => '`createdAt` DESC',
            'fields' => [
                'code' => ['label' => 'Code', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'year' => ['label' => 'Year', 'type' => 'number'],
                'active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
        ],
        'categories' => [
            'label' => 'Categories',
            'table' => 'categories',
            'primary_key' => 'id',
            'key_type' => 'string',
            'timestamps' => ['createdAt', 'updatedAt'],
            'list_columns' => ['name', 'slug', 'active', 'order'],
            'default_sort' => '`order` ASC, `createdAt` DESC',
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
                'slug' => ['label' => 'Slug', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'imageUrl' => ['label' => 'Image URL', 'type' => 'text'],
                'parentId' => ['label' => 'Parent Category ID', 'type' => 'text'],
                'order' => ['label' => 'Display Order', 'type' => 'number'],
                'active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
        ],
        'products' => [
            'label' => 'Products',
            'table' => 'products',
            'primary_key' => 'id',
            'key_type' => 'string',
            'timestamps' => ['createdAt', 'updatedAt'],
            'list_columns' => ['name', 'sku', 'price', 'currency', 'type', 'active'],
            'default_sort' => '`createdAt` DESC',
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'required' => true],
                'price' => ['label' => 'Price', 'type' => 'number', 'required' => true],
                'currency' => ['label' => 'Currency', 'type' => 'text'],
                'sku' => ['label' => 'SKU', 'type' => 'text', 'required' => true],
                'type' => ['label' => 'Type', 'type' => 'text', 'required' => true],
                'fileUrl' => ['label' => 'File URL (Optional Download)', 'type' => 'text'],
                'imageurl' => ['label' => 'Primary Display Image', 'type' => 'image'],
                'categoryId' => ['label' => 'Product Category', 'type' => 'select', 'options' => []], // Options populated in controller
                'stock' => ['label' => 'Available Stock Quantity', 'type' => 'number'],
                'previousprice' => ['label' => 'Strike-through Price (Original)', 'type' => 'number'],
                'specialprice' => ['label' => 'Special Event Price (Current)', 'type' => 'number'],
                'specialevent' => ['label' => 'Special Offer Occasion (e.g. Black Friday)', 'type' => 'text'],
                'specialactive' => ['label' => 'Activate Special Pricing', 'type' => 'boolean'],
                'active' => ['label' => 'Visible in Marketplace', 'type' => 'boolean'],
            ],
        ],
        'orders' => [
            'label' => 'Orders',
            'table' => 'orders',
            'primary_key' => 'id',
            'key_type' => 'string',
            'timestamps' => ['createdAt', 'updatedAt'],
            'list_columns' => ['userId', 'total', 'currency', 'status', 'createdAt'],
            'default_sort' => '`createdAt` DESC',
            'fields' => [
                'userId' => ['label' => 'User ID', 'type' => 'text', 'required' => true],
                'stripePaymentId' => ['label' => 'Payment Reference', 'type' => 'text'],
                'total' => ['label' => 'Total', 'type' => 'number', 'required' => true],
                'currency' => ['label' => 'Currency', 'type' => 'text'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['PENDING', 'PAID', 'FAILED', 'CANCELLED'], 'required' => true],
            ],
        ],
        'order_items' => [
            'label' => 'Order Items',
            'table' => 'order_items',
            'primary_key' => 'id',
            'key_type' => 'string',
            'list_columns' => ['orderId', 'productId', 'quantity', 'price'],
            'default_sort' => '`orderId` ASC',
            'fields' => [
                'orderId' => ['label' => 'Order ID', 'type' => 'text', 'required' => true],
                'productId' => ['label' => 'Product ID', 'type' => 'text', 'required' => true],
                'quantity' => ['label' => 'Quantity', 'type' => 'number', 'required' => true],
                'price' => ['label' => 'Unit Price', 'type' => 'number', 'required' => true],
            ],
        ],
        'users' => [
            'label' => 'Users',
            'table' => 'users',
            'primary_key' => 'id',
            'key_type' => 'string',
            'timestamps' => ['createdAt', 'updatedAt'],
            'list_columns' => ['email', 'name', 'role', 'createdAt'],
            'default_sort' => '`createdAt` DESC',
            'fields' => [
                'email' => ['label' => 'Email', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Name', 'type' => 'text'],
                'image' => ['label' => 'Profile Image', 'type' => 'image'],
                'role' => ['label' => 'Role', 'type' => 'select', 'options' => ['USER', 'ADMIN', 'PARTNER'], 'required' => true],
                'password' => ['label' => 'Password', 'type' => 'password', 'hash' => true],
            ],
        ],
        'leads' => [
            'label' => 'Leads',
            'table' => 'leads',
            'primary_key' => 'id',
            'key_type' => 'string',
            'timestamps' => ['createdAt', 'updatedAt'],
            'list_columns' => ['companyName', 'contactName', 'contactEmail', 'status', 'assignedPartnerId'],
            'default_sort' => '`createdAt` DESC',
            'fields' => [
                'isoStandardId' => ['label' => 'ISO Standard ID', 'type' => 'text', 'required' => true],
                'companyName' => ['label' => 'Company Name', 'type' => 'text', 'required' => true],
                'contactName' => ['label' => 'Contact Name', 'type' => 'text', 'required' => true],
                'contactEmail' => ['label' => 'Contact Email', 'type' => 'text', 'required' => true],
                'contactPhone' => ['label' => 'Contact Phone', 'type' => 'text'],
                'companySize' => ['label' => 'Company Size', 'type' => 'text'],
                'currentStatus' => ['label' => 'Current Status', 'type' => 'textarea'],
                'requirements' => ['label' => 'Requirements', 'type' => 'textarea'],
                'status' => ['label' => 'Lead Status', 'type' => 'text'],
                'assignedPartnerId' => ['label' => 'Assigned Partner User ID', 'type' => 'text'],
                'notes' => ['label' => 'Notes', 'type' => 'textarea'],
            ],
        ],
        'nominations' => [
            'label' => 'Nominations',
            'table' => 'nominations',
            'primary_key' => 'id',
            'key_type' => 'string',
            'timestamps' => ['createdAt', 'updatedAt'],
            'list_columns' => ['nominatorName', 'nomineeName', 'nominationType', 'status', 'createdAt'],
            'default_sort' => '`createdAt` DESC',
            'fields' => [
                'nominatorName' => ['label' => 'Nominator Name', 'type' => 'text', 'required' => true],
                'nominatorEmail' => ['label' => 'Nominator Email', 'type' => 'text', 'required' => true],
                'nomineeName' => ['label' => 'Nominee Name', 'type' => 'text', 'required' => true],
                'nomineeEmail' => ['label' => 'Nominee Email', 'type' => 'text'],
                'nominationType' => ['label' => 'Nomination Type', 'type' => 'text', 'required' => true],
                'reason' => ['label' => 'Reason', 'type' => 'textarea', 'required' => true],
                'status' => ['label' => 'Status', 'type' => 'text'],
            ],
        ],
        'certification_requests' => [
            'label' => 'Certification Requests',
            'table' => 'certification_requests',
            'primary_key' => 'id',
            'key_type' => 'string',
            'timestamps' => ['createdAt', 'updatedAt'],
            'list_columns' => ['companyName', 'contactName', 'contactEmail', 'status', 'createdAt'],
            'default_sort' => '`createdAt` DESC',
            'fields' => [
                'companyName' => ['label' => 'Company Name', 'type' => 'text', 'required' => true],
                'contactName' => ['label' => 'Contact Name', 'type' => 'text', 'required' => true],
                'contactEmail' => ['label' => 'Contact Email', 'type' => 'text', 'required' => true],
                'contactPhone' => ['label' => 'Contact Phone', 'type' => 'text'],
                'companySize' => ['label' => 'Company Size', 'type' => 'text'],
                'currentStatus' => ['label' => 'Current Status', 'type' => 'textarea'],
                'requirements' => ['label' => 'Requirements', 'type' => 'textarea'],
                'status' => ['label' => 'Status', 'type' => 'text'],
            ],
        ],
        'site_settings' => [
            'label' => 'Site Settings',
            'table' => 'site_settings',
            'primary_key' => 'id',
            'key_type' => 'string',
            'timestamps' => ['createdAt', 'updatedAt'],
            'list_columns' => ['key', 'label', 'category', 'type', 'ispublic'],
            'default_sort' => '`category` ASC, `key` ASC',
            'fields' => [
                'key' => ['label' => 'Key', 'type' => 'text', 'required' => true],
                'label' => ['label' => 'Label', 'type' => 'text'],
                'value' => ['label' => 'Value', 'type' => 'textarea'],
                'category' => [
                    'label' => 'Category',
                    'type' => 'select',
                    'options' => [
                        'general',
                        'users',
                        'users_access',
                        'appearance',
                        'theme',
                        'appearance_theme',
                        'inventory',
                        'ecommerce',
                        'iso',
                        'iso_compliance',
                        'documents',
                        'notifications',
                        'security',
                        'integrations',
                        'audit',
                        'audit_logs',
                    ],
                ],
                'type' => [
                    'label' => 'Type',
                    'type' => 'select',
                    'options' => [
                        'text',
                        'textarea',
                        'boolean',
                        'number',
                        'json',
                        'select',
                        'file',
                    ],
                ],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'ispublic' => ['label' => 'Public', 'type' => 'boolean'],
                'requiresrestart' => ['label' => 'Requires Restart', 'type' => 'boolean'],
            ],
        ],
        'about_us' => [
            'label' => 'About Us',
            'table' => 'about_us',
            'primary_key' => 'id',
            'key_type' => 'int',
            'auto_increment' => true,
            'timestamps' => ['updated_at'],
            'list_columns' => ['id', 'tagline', 'updated_at'],
            'default_sort' => 'id ASC',
            'fields' => [
                'tagline' => ['label' => 'Tagline', 'type' => 'text'],
                'vision' => ['label' => 'Vision', 'type' => 'textarea'],
                'mission' => ['label' => 'Mission', 'type' => 'textarea'],
                'services' => ['label' => 'Services', 'type' => 'textarea'],
            ],
        ],
        'terms_and_conditions' => [
            'label' => 'Terms',
            'table' => 'terms_and_conditions',
            'primary_key' => 'id',
            'key_type' => 'int',
            'auto_increment' => true,
            'timestamps' => ['created_at'],
            'list_columns' => ['title', 'version', 'is_active', 'created_at'],
            'default_sort' => 'created_at DESC',
            'fields' => [
                'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
                'version' => ['label' => 'Version', 'type' => 'text', 'required' => true],
                'content' => ['label' => 'Content', 'type' => 'textarea', 'required' => true],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
        ],
        'partners' => [
            'label' => 'Partners',
            'table' => 'partners',
            'primary_key' => 'id',
            'key_type' => 'int',
            'auto_increment' => true,
            'timestamps' => ['created_at'],
            'list_columns' => ['name', 'url', 'created_at'],
            'default_sort' => 'created_at DESC',
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
                'url' => ['label' => 'URL', 'type' => 'text'],
                'logo_url' => ['label' => 'Logo', 'type' => 'image', 'required' => true],
            ],
        ],
        'product_images' => [
            'label' => 'Product Images',
            'table' => 'product_images',
            'primary_key' => 'id',
            'key_type' => 'int',
            'auto_increment' => true,
            'timestamps' => ['created_at'],
            'list_columns' => ['product_id', 'sort_order', 'created_at'],
            'default_sort' => 'product_id ASC, sort_order ASC, created_at DESC',
            'fields' => [
                'product_id' => ['label' => 'Product ID', 'type' => 'text', 'required' => true],
                'image_url' => ['label' => 'Gallery Image', 'type' => 'image', 'required' => true],
                'sort_order' => ['label' => 'Sort Order', 'type' => 'number'],
            ],
        ],
        'product_recommendations' => [
            'label' => 'Product Recommendations',
            'table' => 'product_recommendations',
            'primary_key' => 'id',
            'key_type' => 'int',
            'auto_increment' => true,
            'timestamps' => ['created_at'],
            'list_columns' => ['product_id', 'recommended_product_id', 'sort_order', 'created_at'],
            'default_sort' => 'product_id ASC, sort_order ASC, created_at DESC',
            'fields' => [
                'product_id' => ['label' => 'Product ID', 'type' => 'text', 'required' => true],
                'recommended_product_id' => ['label' => 'Recommended Product ID', 'type' => 'text', 'required' => true],
                'sort_order' => ['label' => 'Sort Order', 'type' => 'number'],
            ],
        ],
        'hero_slides' => [
            'label' => 'Hero Slides',
            'table' => 'hero_slides',
            'primary_key' => 'id',
            'key_type' => 'int',
            'auto_increment' => true,
            'timestamps' => ['created_at'],
            'list_columns' => ['title', 'subtitle', 'sort_order', 'active', 'created_at'],
            'default_sort' => 'sort_order ASC, created_at DESC',
            'fields' => [
                'title'       => ['label' => 'Slide Title',       'type' => 'text',     'required' => true],
                'subtitle'    => ['label' => 'Subtitle / Label',  'type' => 'text'],
                'description' => ['label' => 'Description',       'type' => 'textarea'],
                'image_url'   => ['label' => 'Slide Image',       'type' => 'image',    'required' => true],
                'cta_text'    => ['label' => 'Primary Button Text', 'type' => 'text'],
                'cta_link'    => ['label' => 'Primary Button Link', 'type' => 'text'],
                'secondary_cta_text' => ['label' => 'Secondary Button Text', 'type' => 'text'],
                'secondary_cta_link' => ['label' => 'Secondary Button Link', 'type' => 'text'],
                'sort_order'  => ['label' => 'Sort Order',        'type' => 'number'],
                'active'      => ['label' => 'Active',            'type' => 'boolean'],
            ],
        ],
    ],
];
